version: "3.9"

services:
#  web:
#      container_name: web-${APP_NAME}
#      hostname: web-${APP_NAME}
#      restart: always
#      image: web-${APP_NAME}
#      ports:
#        - "5000:5000"
#
#      environment:
#        - ./.env
#      depends_on:
#        db:
#          condition: service_healthy
#      build:
#        dockerfile: Dockerfile
#        context: .

  db:
      image: postgres:14.2
      ports:
        - "5432:5432"
      env_file:
          - ./.env
      restart: always
      container_name: db-${APP_NAME}
      hostname: host-${APP_NAME}
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
          - db_data_prod:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 15s
        timeout: 15s
        retries: 25


volumes:
  db_data_prod: